kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.adotCollector.clusterRoleBindingName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.adotCollector.serviceAccountName }}
  namespace: {{ .Values.adotCollector.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.adotCollector.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
