apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-aws-auth-configmap
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resourceNames:
  - aws-auth
  resources:
  - configmaps
  verbs:
  - get